platform :"ios", "7.0"

pod "AFNetworking"
pod "MBProgressHUD"
pod "MJRefresh"
pod "MJExtension"
pod "FSCalendar"
pod "SDWebImage"
pod "JDStatusBarNotification"
pod "NJKWebViewProgress"
pod "TPKeyboardAvoiding"
pod "ReactiveCocoa"